// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AppSalud.Models;
//
//    var imc = Imc.FromJson(jsonString);

namespace AppSalud.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class IMC_Model
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("fechaRegistro")]
        public DateTimeOffset FechaRegistro { get; set; }

        [JsonProperty("peso")]
        public float Peso { get; set; }

        [JsonProperty("altura")]
        public float Altura { get; set; }

        [JsonProperty("imc")]
        public float ImcImc { get; set; }
    }

    public partial class IMC_Model
    {
        public static IMC_Model FromJson(string json) => JsonConvert.DeserializeObject<IMC_Model>(json, AppSalud.Models.Converter.Settings);
    }

    public static class SerializeIMC
    {
        public static string ToJson(this IMC_Model self) => JsonConvert.SerializeObject(self, AppSalud.Models.Converter.Settings);
    }

    internal static class ConverterIMC
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
