// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Listing.App.Models;
//
//    var favorite = Favorite.FromJson(jsonString);

namespace Listing.App.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Favorite
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("userId")]
        public long UserId { get; set; }

        [JsonProperty("listId")]
        public long ListId { get; set; }

        [JsonProperty("registrationDate")]
        public DateTimeOffset RegistrationDate { get; set; }
    }

    public partial class Favorite
    {
        public static Favorite FromJson(string json) => JsonConvert.DeserializeObject<Favorite>(json, Listing.App.Models.Converter.Settings);
    }

    public static class SerializeFav
    {
        public static string ToJson(this Favorite self) => JsonConvert.SerializeObject(self, Listing.App.Models.Converter.Settings);
    }

    internal static class ConverterFav
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
