// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Listing.App.Models;
//
//    var listModel = ListModel.FromJson(jsonString);

namespace Listing.App.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ListModel
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("ownerId")]
        public long OwnerId { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("registrationDate")]
        public DateTimeOffset RegistrationDate { get; set; }
    }

    public partial class ListModel
    {
        public static List<ListModel> FromJson(string json) => JsonConvert.DeserializeObject<List<ListModel>>(json, Listing.App.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<ListModel> self) => JsonConvert.SerializeObject(self, Listing.App.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
