// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Listing.App.Models;
//
//    var listCreation = ListCreation.FromJson(jsonString);

namespace Listing.App.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ListCreation
    {
        [JsonProperty("OwnerId")]
        public long OwnerId { get; set; }

        [JsonProperty("Title")]
        public string Title { get; set; }
    }

    public partial class ListCreation
    {
        public static ListCreation FromJson(string json) => JsonConvert.DeserializeObject<ListCreation>(json, Listing.App.Models.Converter.Settings);
    }

    public static class SerializeLCreation
    {
        public static string ToJson(this ListCreation self) => JsonConvert.SerializeObject(self, Listing.App.Models.Converter.Settings);
    }

    internal static class ConverterLCreation
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
